### ISSUE TITLE
I am impatient and want to queue a build before it is green

### ISSUE THREAD

**Issue by Noviny** [atlassian/landkid#8]
Have a way to have a 'merge once green'

Likely behaviour, have a queue of builds to add to the general queue once they go green.

Queues of queues!

Alternatively, add it to the queue, but every time you want to take anything off the queueueueue it is skipped if it is not finished, and punted from the q if it fails.

**Comment by jamiebuilds** [comment]
I would also like this.

Requirements:

- Button to "auto-queue when ready" is disabled until latest commit has approvals
- Cannot click if there are non-pending failed conditions (currently failed build)
- Click to auto-queue when all currently pending necessary conditions for the current commit are met
- New commits should invalidate the auto-queue and should require clicking again
- While we're waiting for all the pending conditions, show a button to undo request
- If one of the pending conditions turns into a failing state, reject "auto-queue" request

**Comment by lukebatchelor** [comment]
DONE
